#include "black_internal.h"

typedef struct { char *buf; size_t len,cap; BlackError *err; } G;
static int put(G*g,const char*s){size_t n=strlen(s);if(g->len+n+1>g->cap){size_t c=g->cap?g->cap*2:4096;while(c<g->len+n+1)c*=2;char*b=realloc(g->buf,c);if(!b)return -1;g->buf=b;g->cap=c;}memcpy(g->buf+g->len,s,n);g->len+=n;g->buf[g->len]=0;return 0;}
static int fmt(G*g,const char*f,...){char b[1024];va_list a;va_start(a,f);int n=vsnprintf(b,sizeof(b),f,a);va_end(a);if(n<0)return -1;if((size_t)n<sizeof(b))return put(g,b);char*x=malloc((size_t)n+1);va_start(a,f);vsnprintf(x,(size_t)n+1,f,a);va_end(a);int r=put(g,x);free(x);return r;}
static const char* tn(const BlackType*t){if(!t)return "void";switch(t->kind){case BLACK_TYPE_VOID:return "void";case BLACK_TYPE_BOOL:return "_Bool";case BLACK_TYPE_U8:return "uint8_t";case BLACK_TYPE_U16:return "uint16_t";case BLACK_TYPE_U32:return "uint32_t";case BLACK_TYPE_U64:return "uint64_t";case BLACK_TYPE_I8:return "int8_t";case BLACK_TYPE_I16:return "int16_t";case BLACK_TYPE_I32:return "int32_t";case BLACK_TYPE_I64:return "int64_t";case BLACK_TYPE_USIZE:return "uintptr_t";case BLACK_TYPE_ISIZE:return "intptr_t";case BLACK_TYPE_STRUCT:return t->as.record.name;default:return "void";}}
static int type_decl(G*g,const BlackType*t,const char*n){
    if(t->kind==BLACK_TYPE_POINTER){
        if(t->as.pointer.base->kind==BLACK_TYPE_FUNCTION){
            put(g,tn(t->as.pointer.base->as.function.return_type)); put(g," (*"); put(g,n); put(g,")(");
            for(size_t i=0;i<t->as.pointer.base->as.function.param_count;i++){if(i)put(g,", ");put(g,tn(t->as.pointer.base->as.function.params[i]));} return put(g,")");
        }
        put(g,tn(t->as.pointer.base)); if(t->is_const)put(g," const"); if(t->is_volatile)put(g," volatile"); return fmt(g," *%s",n);
    }
    if(t->kind==BLACK_TYPE_FUNCTION){
        put(g,tn(t->as.function.return_type)); put(g," (*"); put(g,n); put(g,")(");
        for(size_t i=0;i<t->as.function.param_count;i++){if(i)put(g,", ");put(g,tn(t->as.function.params[i]));} return put(g,")");
    }
    if(t->kind==BLACK_TYPE_ARRAY)return fmt(g,"%s %s[%zu]",tn(t->as.array.element),n,t->as.array.count);
    return fmt(g,"%s %s",tn(t),n);
}
static int ex(G*g,BlackExpr*e){if(!e)return put(g,"0");switch(e->kind){case BLACK_EXPR_INT:return fmt(g,"%llu",(unsigned long long)e->as.integer);case BLACK_EXPR_BOOL:return put(g,e->as.boolean?"1":"0");case BLACK_EXPR_CHAR:return fmt(g,"'%c'",e->as.character);case BLACK_EXPR_STRING:{put(g,"\"");put(g,e->as.string);return put(g,"\"");}case BLACK_EXPR_NAME:return put(g,e->as.name);case BLACK_EXPR_UNARY:{const char*o=e->as.unary.op==BLACK_UN_NEG?"-":e->as.unary.op==BLACK_UN_NOT?"!":e->as.unary.op==BLACK_UN_BITNOT?"~":e->as.unary.op==BLACK_UN_DEREF?"*":"&";put(g,o);put(g,"(");ex(g,e->as.unary.value);return put(g,")");}case BLACK_EXPR_BINARY:{const char*o="+";switch(e->as.binary.op){case BLACK_BIN_SUB:o="-";break;case BLACK_BIN_MUL:o="*";break;case BLACK_BIN_DIV:o="/";break;case BLACK_BIN_MOD:o="%";break;case BLACK_BIN_EQ:o="==";break;case BLACK_BIN_NE:o="!=";break;case BLACK_BIN_LT:o="<";break;case BLACK_BIN_LE:o="<=";break;case BLACK_BIN_GT:o=">";break;case BLACK_BIN_GE:o=">=";break;case BLACK_BIN_AND:o="&";break;case BLACK_BIN_OR:o="|";break;case BLACK_BIN_XOR:o="^";break;case BLACK_BIN_LOGICAL_AND:o="&&";break;case BLACK_BIN_LOGICAL_OR:o="||";break;default:break;}put(g,"(");ex(g,e->as.binary.left);fmt(g," %s ",o);ex(g,e->as.binary.right);return put(g,")");}case BLACK_EXPR_ASSIGN:ex(g,e->as.assign.left);put(g," = ");return ex(g,e->as.assign.right);case BLACK_EXPR_CALL:ex(g,e->as.call.callee);put(g,"(");for(size_t i=0;i<e->as.call.arg_count;i++){if(i)put(g,", ");ex(g,e->as.call.args[i]);}return put(g,")");case BLACK_EXPR_INDEX:ex(g,e->as.index.base);put(g,"[");ex(g,e->as.index.index);return put(g,"]");case BLACK_EXPR_MEMBER:ex(g,e->as.member.base);put(g,".");return put(g,e->as.member.member);default:return put(g,"0");}}
static int stmt(G*g,BlackStmt*s,int ind){if(!s)return 0;for(int i=0;i<ind;i++)put(g,"    ");switch(s->kind){case BLACK_ST_BLOCK:put(g,"{\n");for(size_t i=0;i<s->as.block.count;i++)stmt(g,s->as.block.items[i],ind+1);for(int i=0;i<ind;i++)put(g,"    ");return put(g,"}\n");case BLACK_ST_LET:if(s->as.let.is_static)put(g,"static ");if(s->as.let.is_const)put(g,"const ");if(s->as.let.is_volatile)put(g,"volatile ");type_decl(g,s->as.let.type,s->as.let.name);if(s->as.let.initializer){put(g," = ");if(s->as.let.type->kind==BLACK_TYPE_POINTER && s->as.let.initializer->kind==BLACK_EXPR_INT)put(g,"(void *)(uintptr_t)");ex(g,s->as.let.initializer);}return put(g,";\n");case BLACK_ST_EXPR:ex(g,s->as.expr.expr);return put(g,";\n");case BLACK_ST_RETURN:put(g,"return");if(s->as.ret.expr){put(g," ");ex(g,s->as.ret.expr);}return put(g,";\n");case BLACK_ST_IF:put(g,"if (");ex(g,s->as.if_stmt.condition);put(g,") ");stmt(g,s->as.if_stmt.then_branch,ind);if(s->as.if_stmt.else_branch){for(int i=0;i<ind;i++)put(g,"    ");put(g,"else ");stmt(g,s->as.if_stmt.else_branch,ind);}return 0;case BLACK_ST_WHILE:put(g,"while (");ex(g,s->as.while_stmt.condition);put(g,") ");return stmt(g,s->as.while_stmt.body,ind);default:return 0;}}
int black_codegen_c(const BlackProgram*p,char*out,size_t outsz,BlackError*er){G g={0};if(put(&g,"/* Generated by Black compiler. Freestanding-safe: no libc calls are emitted by the language itself. */\n#include <stdint.h>\n#include <stddef.h>\n#include <stdbool.h>\n\n")<0)return -1;if(p->target)fmt(&g,"/* target: %s */\n",p->target);if(p->abi)fmt(&g,"/* ABI: %s */\n",p->abi);for(size_t i=0;i<p->count;i++)if(p->decls[i]->kind==BLACK_DECL_SPEC)fmt(&g,"/* spec: %s */\n",p->decls[i]->as.spec.text?p->decls[i]->as.spec.text:"");
for(size_t i=0;i<p->count;i++){BlackDecl*d=p->decls[i];if(d->kind==BLACK_DECL_STRUCT){fmt(&g,"typedef struct %s %s;\nstruct %s {\n",d->name,d->name,d->name);for(size_t j=0;j<d->as.structure.field_count;j++){put(&g,"    ");type_decl(&g,d->as.structure.fields[j].type,d->as.structure.fields[j].name);put(&g,";\n");}put(&g,"};\n\n");}else if(d->kind==BLACK_DECL_ENUM){fmt(&g,"typedef enum %s {\n",d->name);for(size_t j=0;j<d->as.enumeration.value_count;j++)fmt(&g,"    %s%s\n",d->as.enumeration.values[j].name,j+1<d->as.enumeration.value_count?",":"");fmt(&g,"} %s;\n\n",d->name);}}
for(size_t i=0;i<p->count;i++){BlackDecl*d=p->decls[i];if(d->kind==BLACK_DECL_EXTERN_VAR){put(&g,"extern ");if(d->as.extern_var.is_const)put(&g,"const ");if(d->as.extern_var.is_volatile)put(&g,"volatile ");type_decl(&g,d->as.extern_var.type,d->name);put(&g,";\n");}}

for(size_t i=0;i<p->count;i++){BlackDecl*d=p->decls[i];if(d->kind!=BLACK_DECL_FUNCTION)continue;BlackType*ft=d->as.function.return_type;if(d->as.function.section)fmt(&g,"__attribute__((section(\"%s\"))) ",d->as.function.section);if(d->as.function.interrupt_arch)put(&g,"__attribute__((interrupt)) ");if(d->as.function.is_static)put(&g,"static ");if(d->as.function.is_inline)put(&g,"inline ");if(d->as.function.is_extern)put(&g,"extern ");if(d->as.function.is_unsafe)put(&g,"/* unsafe */ ");fmt(&g,"%s %s(",tn(ft),d->name);for(size_t j=0;j<d->as.function.param_count;j++){if(j)put(&g,", ");type_decl(&g,d->as.function.params[j].type,d->as.function.params[j].name);}put(&g,") ");if(d->as.function.is_extern||!d->as.function.body){put(&g,";\n\n");continue;}stmt(&g,d->as.function.body,0);put(&g,"\n");}
if(g.len+1>outsz){black_set_error(er,(BlackLocation){0},"generated C exceeds output buffer (%zu bytes required)",g.len+1);free(g.buf);return -1;}memcpy(out,g.buf,g.len+1);free(g.buf);return 0;}
const char *black_type_name(const BlackType*t){static char b[128];if(!t){return "<null>";}switch(t->kind){case BLACK_TYPE_VOID:return "void";case BLACK_TYPE_BOOL:return "bool";case BLACK_TYPE_U8:return "u8";case BLACK_TYPE_U16:return "u16";case BLACK_TYPE_U32:return "u32";case BLACK_TYPE_U64:return "u64";case BLACK_TYPE_I8:return "i8";case BLACK_TYPE_I16:return "i16";case BLACK_TYPE_I32:return "i32";case BLACK_TYPE_I64:return "i64";case BLACK_TYPE_USIZE:return "usize";case BLACK_TYPE_ISIZE:return "isize";case BLACK_TYPE_POINTER:snprintf(b,sizeof(b),"*%s",black_type_name(t->as.pointer.base));return b;case BLACK_TYPE_ARRAY:snprintf(b,sizeof(b),"[%zu]%s",t->as.array.count,black_type_name(t->as.array.element));return b;case BLACK_TYPE_STRUCT:return t->as.record.name;default:return "function";}}
