#include "black_internal.h"

typedef struct { const BlackTokenList *ts; size_t i; BlackError *err; } P;
static BlackToken *cur(P*p){return p->i<p->ts->count?(BlackToken*)&p->ts->items[p->i]:NULL;}
static int is(P*p,BlackTokenKind k){return cur(p)&&cur(p)->kind==k;}
static BlackToken *eat(P*p,BlackTokenKind k){if(is(p,k)){BlackToken*t=(BlackToken*)&p->ts->items[p->i++];return t;}if(cur(p))black_set_error(p->err,cur(p)->location,"expected %s, got %s",black_token_name(k),black_token_name(cur(p)->kind));return NULL;}
static char* text(P*p){BlackToken*t=cur(p);return t?black_xstrndup(t->text,t->length):NULL;}
static BlackType* type(P*p);
static BlackExpr* expr(P*p,int minprec);

static BlackType* type(P*p){
    int c=0,v=0; if(is(p,BLACK_T_CONST)){eat(p,BLACK_T_CONST);c=1;} if(is(p,BLACK_T_VOLATILE)){eat(p,BLACK_T_VOLATILE);v=1;}
    size_t ptr_depth=0; while(is(p,BLACK_T_STAR)){eat(p,BLACK_T_STAR);ptr_depth++;}
    BlackType*t=NULL; BlackTokenKind k=cur(p)?cur(p)->kind:BLACK_T_EOF;
    switch(k){
        case BLACK_T_VOID:t=black_type_new(BLACK_TYPE_VOID);break; case BLACK_T_BOOL:t=black_type_new(BLACK_TYPE_BOOL);break;
        case BLACK_T_U8:t=black_type_new(BLACK_TYPE_U8);break; case BLACK_T_U16:t=black_type_new(BLACK_TYPE_U16);break; case BLACK_T_U32:t=black_type_new(BLACK_TYPE_U32);break; case BLACK_T_U64:t=black_type_new(BLACK_TYPE_U64);break;
        case BLACK_T_I8:t=black_type_new(BLACK_TYPE_I8);break; case BLACK_T_I16:t=black_type_new(BLACK_TYPE_I16);break; case BLACK_T_I32:t=black_type_new(BLACK_TYPE_I32);break; case BLACK_T_I64:t=black_type_new(BLACK_TYPE_I64);break;
        case BLACK_T_USIZE:t=black_type_new(BLACK_TYPE_USIZE);break; case BLACK_T_ISIZE:t=black_type_new(BLACK_TYPE_ISIZE);break;
        case BLACK_T_ID:{char*n=text(p);eat(p,BLACK_T_ID);t=black_type_new(BLACK_TYPE_STRUCT);t->as.record.name=n;break;}
        case BLACK_T_FN:{
            eat(p,BLACK_T_FN); t=black_type_new(BLACK_TYPE_FUNCTION); eat(p,BLACK_T_LPAREN);
            while(!is(p,BLACK_T_RPAREN)){BlackType*q=type(p);if(!q){black_type_free(t);return NULL;}t->as.function.params=realloc(t->as.function.params,(t->as.function.param_count+1)*sizeof(*t->as.function.params));t->as.function.params[t->as.function.param_count++]=q;if(is(p,BLACK_T_COMMA))eat(p,BLACK_T_COMMA);else break;}
            eat(p,BLACK_T_RPAREN);t->as.function.return_type=black_type_new(BLACK_TYPE_VOID);if(is(p,BLACK_T_ARROW)){eat(p,BLACK_T_ARROW);black_type_free(t->as.function.return_type);t->as.function.return_type=type(p);}break;
        }
        default:if(cur(p))black_set_error(p->err,cur(p)->location,"expected a type");return NULL;
    }
    if(k!=BLACK_T_ID&&k!=BLACK_T_FN)eat(p,k);
    t->is_const=c;t->is_volatile=v;
    while(ptr_depth--){BlackType*n=black_type_new(BLACK_TYPE_POINTER);n->as.pointer.base=t;t=n;}
    if(is(p,BLACK_T_LBRACKET)){eat(p,BLACK_T_LBRACKET);if(!is(p,BLACK_T_NUMBER)){black_set_error(p->err,cur(p)->location,"array type requires a constant length");black_type_free(t);return NULL;}size_t n=(size_t)cur(p)->number;eat(p,BLACK_T_NUMBER);eat(p,BLACK_T_RBRACKET);BlackType*a=black_type_new(BLACK_TYPE_ARRAY);a->as.array.element=t;a->as.array.count=n;t=a;}
    return t;
}
static BlackExpr* newe(BlackExprKind k,P*p){BlackExpr*e=calloc(1,sizeof(*e));e->kind=k;if(cur(p))e->location=cur(p)->location;return e;}
static int prec(BlackTokenKind k){switch(k){case BLACK_T_ASSIGN:return 1;case BLACK_T_OR_OR:return 2;case BLACK_T_AND_AND:return 3;case BLACK_T_PIPE:return 4;case BLACK_T_CARET:return 5;case BLACK_T_AMP:return 6;case BLACK_T_EQ:case BLACK_T_NE:return 7;case BLACK_T_LT:case BLACK_T_LE:case BLACK_T_GT:case BLACK_T_GE:return 8;case BLACK_T_PLUS:case BLACK_T_MINUS:return 9;case BLACK_T_STAR:case BLACK_T_SLASH:case BLACK_T_PERCENT:return 10;default:return 0;}}
static BlackBinaryOp bop(BlackTokenKind k){switch(k){case BLACK_T_PLUS:return BLACK_BIN_ADD;case BLACK_T_MINUS:return BLACK_BIN_SUB;case BLACK_T_STAR:return BLACK_BIN_MUL;case BLACK_T_SLASH:return BLACK_BIN_DIV;case BLACK_T_PERCENT:return BLACK_BIN_MOD;case BLACK_T_EQ:return BLACK_BIN_EQ;case BLACK_T_NE:return BLACK_BIN_NE;case BLACK_T_LT:return BLACK_BIN_LT;case BLACK_T_LE:return BLACK_BIN_LE;case BLACK_T_GT:return BLACK_BIN_GT;case BLACK_T_GE:return BLACK_BIN_GE;case BLACK_T_AMP:return BLACK_BIN_AND;case BLACK_T_PIPE:return BLACK_BIN_OR;case BLACK_T_CARET:return BLACK_BIN_XOR;case BLACK_T_AND_AND:return BLACK_BIN_LOGICAL_AND;case BLACK_T_OR_OR:return BLACK_BIN_LOGICAL_OR;default:return BLACK_BIN_ADD;}}
static BlackExpr* primary(P*p){
    if(is(p,BLACK_T_NUMBER)){BlackExpr*e=newe(BLACK_EXPR_INT,p);e->as.integer=cur(p)->number;eat(p,BLACK_T_NUMBER);return e;}
    if(is(p,BLACK_T_STRING)){BlackExpr*e=newe(BLACK_EXPR_STRING,p);e->as.string=black_xstrndup(cur(p)->text+1,cur(p)->length>=2?cur(p)->length-2:0);eat(p,BLACK_T_STRING);return e;}
    if(is(p,BLACK_T_CHAR)){BlackExpr*e=newe(BLACK_EXPR_CHAR,p);e->as.character=cur(p)->length>=3?cur(p)->text[1]:0;eat(p,BLACK_T_CHAR);return e;}
    if(is(p,BLACK_T_TRUE)||is(p,BLACK_T_FALSE)){BlackExpr*e=newe(BLACK_EXPR_BOOL,p);e->as.boolean=is(p,BLACK_T_TRUE);p->i++;return e;}
    if(is(p,BLACK_T_ID)){BlackExpr*e=newe(BLACK_EXPR_NAME,p);e->as.name=text(p);eat(p,BLACK_T_ID);return e;}
    if(is(p,BLACK_T_LPAREN)){eat(p,BLACK_T_LPAREN);BlackExpr*e=expr(p,1);eat(p,BLACK_T_RPAREN);return e;}
    if(cur(p)) { black_set_error(p->err,cur(p)->location,"expected expression"); } return NULL;
}
static BlackExpr* postfix(P*p){BlackExpr*e=NULL;if(is(p,BLACK_T_MINUS)||is(p,BLACK_T_BANG)||is(p,BLACK_T_TILDE)||is(p,BLACK_T_STAR)||is(p,BLACK_T_AMP)){BlackTokenKind k=cur(p)->kind;eat(p,k);BlackExpr*n=newe(BLACK_EXPR_UNARY,p);n->as.unary.op=k==BLACK_T_MINUS?BLACK_UN_NEG:k==BLACK_T_BANG?BLACK_UN_NOT:k==BLACK_T_TILDE?BLACK_UN_BITNOT:k==BLACK_T_STAR?BLACK_UN_DEREF:BLACK_UN_ADDR;n->as.unary.value=postfix(p);e=n;}else e=primary(p);while(e){if(is(p,BLACK_T_LPAREN)){eat(p,BLACK_T_LPAREN);BlackExpr**args=NULL;size_t n=0;if(!is(p,BLACK_T_RPAREN))for(;;){BlackExpr*a=expr(p,1);args=realloc(args,(n+1)*sizeof(*args));args[n++]=a;if(!is(p,BLACK_T_COMMA))break;eat(p,BLACK_T_COMMA);}eat(p,BLACK_T_RPAREN);BlackExpr*nw=newe(BLACK_EXPR_CALL,p);nw->as.call.callee=e;nw->as.call.args=args;nw->as.call.arg_count=n;e=nw;}else if(is(p,BLACK_T_LBRACKET)){eat(p,BLACK_T_LBRACKET);BlackExpr*idx=expr(p,1);eat(p,BLACK_T_RBRACKET);BlackExpr*nw=newe(BLACK_EXPR_INDEX,p);nw->as.index.base=e;nw->as.index.index=idx;e=nw;}else if(is(p,BLACK_T_DOT)){eat(p,BLACK_T_DOT);if(!is(p,BLACK_T_ID))return NULL;BlackExpr*nw=newe(BLACK_EXPR_MEMBER,p);nw->as.member.base=e;nw->as.member.member=text(p);eat(p,BLACK_T_ID);e=nw;}else break;}return e;}
static BlackExpr* expr(P*p,int minprec){BlackExpr*l=postfix(p);if(!l)return NULL;for(;;){BlackTokenKind k=cur(p)?cur(p)->kind:BLACK_T_EOF;int pr=prec(k);if(pr<minprec||!pr)break;eat(p,k);if(k==BLACK_T_ASSIGN){BlackExpr*r=expr(p,pr);BlackExpr*n=newe(BLACK_EXPR_ASSIGN,p);n->as.assign.left=l;n->as.assign.right=r;l=n;continue;}BlackExpr*r=expr(p,pr+1);BlackExpr*n=newe(BLACK_EXPR_BINARY,p);n->as.binary.op=bop(k);n->as.binary.left=l;n->as.binary.right=r;l=n;}return l;}
static BlackStmt* stmt(P*p);
static BlackStmt* block(P*p){BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_BLOCK;s->location=cur(p)?cur(p)->location:(BlackLocation){0};eat(p,BLACK_T_LBRACE);while(cur(p)&&!is(p,BLACK_T_RBRACE)&&!is(p,BLACK_T_EOF)){BlackStmt*x=stmt(p);if(!x){black_stmt_free(s);return NULL;}s->as.block.items=realloc(s->as.block.items,(s->as.block.count+1)*sizeof(*s->as.block.items));s->as.block.items[s->as.block.count++]=x;}eat(p,BLACK_T_RBRACE);return s;}
static BlackStmt* stmt(P*p){
    if(is(p,BLACK_T_LBRACE))return block(p);
    if(is(p,BLACK_T_LET)||is(p,BLACK_T_CONST)||is(p,BLACK_T_STATIC)||is(p,BLACK_T_VOLATILE)){int cn=is(p,BLACK_T_CONST),st=is(p,BLACK_T_STATIC),vo=is(p,BLACK_T_VOLATILE);p->i++;BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_LET;s->location=cur(p)->location;if(!is(p,BLACK_T_ID)){black_set_error(p->err,cur(p)->location,"expected variable name");free(s);return NULL;}s->as.let.name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_COLON);s->as.let.type=type(p);s->as.let.is_const=cn;s->as.let.is_static=st;s->as.let.is_volatile=vo;if(is(p,BLACK_T_ASSIGN)){eat(p,BLACK_T_ASSIGN);s->as.let.initializer=expr(p,1);}eat(p,BLACK_T_SEMI);return s;}
    if(is(p,BLACK_T_ASM)){BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_ASM;s->location=cur(p)->location;eat(p,BLACK_T_ASM);eat(p,BLACK_T_LPAREN);if(!is(p,BLACK_T_STRING)){black_set_error(p->err,cur(p)->location,"asm requires a string");free(s);return NULL;}s->as.asm_stmt.text=black_xstrndup(cur(p)->text+1,cur(p)->length-2);eat(p,BLACK_T_STRING);eat(p,BLACK_T_RPAREN);eat(p,BLACK_T_SEMI);return s;}
    if(is(p,BLACK_T_RETURN)){BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_RETURN;s->location=cur(p)->location;eat(p,BLACK_T_RETURN);if(!is(p,BLACK_T_SEMI))s->as.ret.expr=expr(p,1);eat(p,BLACK_T_SEMI);return s;}
    if(is(p,BLACK_T_IF)){BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_IF;s->location=cur(p)->location;eat(p,BLACK_T_IF);eat(p,BLACK_T_LPAREN);s->as.if_stmt.condition=expr(p,1);eat(p,BLACK_T_RPAREN);s->as.if_stmt.then_branch=stmt(p);if(is(p,BLACK_T_ID)&&cur(p)->length==4&&!memcmp(cur(p)->text,"else",4)){p->i++;s->as.if_stmt.else_branch=stmt(p);}return s;}
    if(is(p,BLACK_T_WHILE)){BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_WHILE;s->location=cur(p)->location;eat(p,BLACK_T_WHILE);eat(p,BLACK_T_LPAREN);s->as.while_stmt.condition=expr(p,1);eat(p,BLACK_T_RPAREN);s->as.while_stmt.body=stmt(p);return s;}
    BlackStmt*s=calloc(1,sizeof(*s));s->kind=BLACK_ST_EXPR;s->location=cur(p)?cur(p)->location:(BlackLocation){0};s->as.expr.expr=expr(p,1);eat(p,BLACK_T_SEMI);return s;
}
static void parse_annotation(P*p,BlackDecl*d){while(is(p,BLACK_T_AT)){eat(p,BLACK_T_AT);if(!is(p,BLACK_T_ID)){black_set_error(p->err,cur(p)->location,"expected annotation name");return;}char*n=text(p);eat(p,BLACK_T_ID);char*v=NULL;if(is(p,BLACK_T_LPAREN)){eat(p,BLACK_T_LPAREN);if(is(p,BLACK_T_STRING)){v=black_xstrndup(cur(p)->text+1,cur(p)->length-2);eat(p,BLACK_T_STRING);}eat(p,BLACK_T_RPAREN);}if(!strcmp(n,"section")){free(d->as.function.section);d->as.function.section=v?v:black_xstrndup("",0);v=NULL;}else if(!strcmp(n,"abi")){free(d->as.function.abi);d->as.function.abi=v?v:black_xstrndup("",0);v=NULL;}else if(!strcmp(n,"interrupt")){free(d->as.function.interrupt_arch);d->as.function.interrupt_arch=v?v:black_xstrndup("",0);v=NULL;}free(v);free(n);}}
static BlackDecl* decl(P*p){
    int isstatic=0,isextern=0,isinline=0,isunsafe=0;while(is(p,BLACK_T_STATIC)||is(p,BLACK_T_EXTERN)||is(p,BLACK_T_INLINE)||is(p,BLACK_T_UNSAFE)){if(is(p,BLACK_T_STATIC))isstatic=1;else if(is(p,BLACK_T_EXTERN))isextern=1;else if(is(p,BLACK_T_INLINE))isinline=1;else isunsafe=1;p->i++;}
    if(is(p,BLACK_T_STRUCT)){BlackDecl*d=calloc(1,sizeof(*d));d->kind=BLACK_DECL_STRUCT;d->location=cur(p)->location;eat(p,BLACK_T_STRUCT);if(!is(p,BLACK_T_ID)){black_set_error(p->err,cur(p)->location,"expected struct name");black_decl_free(d);return NULL;}d->name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_LBRACE);while(!is(p,BLACK_T_RBRACE)&&!is(p,BLACK_T_EOF)){if(!is(p,BLACK_T_ID)){black_set_error(p->err,cur(p)->location,"expected field name");black_decl_free(d);return NULL;}BlackField f={0};f.name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_COLON);f.type=type(p);eat(p,BLACK_T_SEMI);d->as.structure.fields=realloc(d->as.structure.fields,(d->as.structure.field_count+1)*sizeof(f));d->as.structure.fields[d->as.structure.field_count++]=f;}eat(p,BLACK_T_RBRACE);if(is(p,BLACK_T_SEMI))eat(p,BLACK_T_SEMI);return d;}
    if(is(p,BLACK_T_ENUM)){BlackDecl*d=calloc(1,sizeof(*d));d->kind=BLACK_DECL_ENUM;d->location=cur(p)->location;eat(p,BLACK_T_ENUM);if(!is(p,BLACK_T_ID)){black_decl_free(d);return NULL;}d->name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_LBRACE);while(!is(p,BLACK_T_RBRACE)&&!is(p,BLACK_T_EOF)){if(!is(p,BLACK_T_ID)){black_decl_free(d);return NULL;}BlackEnumValue v={0};v.name=text(p);eat(p,BLACK_T_ID);d->as.enumeration.values=realloc(d->as.enumeration.values,(d->as.enumeration.value_count+1)*sizeof(v));d->as.enumeration.values[d->as.enumeration.value_count++]=v;if(is(p,BLACK_T_COMMA)||is(p,BLACK_T_SEMI))p->i++;else break;}eat(p,BLACK_T_RBRACE);if(is(p,BLACK_T_SEMI))eat(p,BLACK_T_SEMI);return d;}
    char *section_prefix=NULL; if(is(p,BLACK_T_SECTION)){eat(p,BLACK_T_SECTION);eat(p,BLACK_T_LPAREN);if(!is(p,BLACK_T_STRING)){black_set_error(p->err,cur(p)->location,"section requires a string");free(section_prefix);return NULL;}section_prefix=black_xstrndup(cur(p)->text+1,cur(p)->length-2);eat(p,BLACK_T_STRING);eat(p,BLACK_T_RPAREN);}
    if(is(p,BLACK_T_FN)){BlackDecl*d=calloc(1,sizeof(*d));d->kind=BLACK_DECL_FUNCTION;d->location=cur(p)->location;d->as.function.is_static=isstatic;d->as.function.is_extern=isextern;d->as.function.is_inline=isinline;d->as.function.is_unsafe=isunsafe;d->as.function.section=section_prefix;eat(p,BLACK_T_FN);if(!is(p,BLACK_T_ID)){black_decl_free(d);return NULL;}d->name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_LPAREN);while(!is(p,BLACK_T_RPAREN)){BlackParam q={0};if(is(p,BLACK_T_CONST)){q.is_const=1;eat(p,BLACK_T_CONST);}if(is(p,BLACK_T_VOLATILE)){q.is_volatile=1;eat(p,BLACK_T_VOLATILE);}if(!is(p,BLACK_T_ID)){black_decl_free(d);return NULL;}q.name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_COLON);q.type=type(p);d->as.function.params=realloc(d->as.function.params,(d->as.function.param_count+1)*sizeof(q));d->as.function.params[d->as.function.param_count++]=q;if(is(p,BLACK_T_COMMA))eat(p,BLACK_T_COMMA);else break;}eat(p,BLACK_T_RPAREN);d->as.function.return_type=black_type_new(BLACK_TYPE_VOID);if(is(p,BLACK_T_ARROW)){eat(p,BLACK_T_ARROW);black_type_free(d->as.function.return_type);d->as.function.return_type=type(p);}parse_annotation(p,d);if(is(p,BLACK_T_SEMI)){eat(p,BLACK_T_SEMI);return d;}d->as.function.body=block(p);return d;}
    if(isextern && is(p,BLACK_T_ID)){BlackDecl*d=calloc(1,sizeof(*d));d->kind=BLACK_DECL_EXTERN_VAR;d->location=cur(p)->location;d->name=text(p);eat(p,BLACK_T_ID);eat(p,BLACK_T_COLON);d->as.extern_var.type=type(p);d->as.extern_var.is_const=0;d->as.extern_var.is_volatile=0;eat(p,BLACK_T_SEMI);return d;}
    if(cur(p)) { black_set_error(p->err,cur(p)->location,"unexpected token %s",black_token_name(cur(p)->kind)); } return NULL;
}
BlackProgram* black_parse(const BlackTokenList*tokens,BlackError*e){P p={tokens,0,e};BlackProgram*pr=calloc(1,sizeof(*pr));while(cur(&p)&&!is(&p,BLACK_T_EOF)){if(is(&p,BLACK_T_SPEC)){BlackDecl*d=calloc(1,sizeof(*d));d->kind=BLACK_DECL_SPEC;d->location=cur(&p)->location;eat(&p,BLACK_T_SPEC);if(is(&p,BLACK_T_STRING)){d->as.spec.text=black_xstrndup(cur(&p)->text+1,cur(&p)->length-2);eat(&p,BLACK_T_STRING);}else if(is(&p,BLACK_T_LBRACE)){eat(&p,BLACK_T_LBRACE);if(is(&p,BLACK_T_STRING)){d->as.spec.text=black_xstrndup(cur(&p)->text+1,cur(&p)->length-2);eat(&p,BLACK_T_STRING);}eat(&p,BLACK_T_RBRACE);}else{black_set_error(e,cur(&p)->location,"spec requires a string or block");black_decl_free(d);black_free_program(pr);return NULL;}if(is(&p,BLACK_T_SEMI))eat(&p,BLACK_T_SEMI);pr->decls=realloc(pr->decls,(pr->count+1)*sizeof(*pr->decls));pr->decls[pr->count++]=d;}else if(is(&p,BLACK_T_KERNEL)){pr->is_kernel=1;eat(&p,BLACK_T_KERNEL);if(!is(&p,BLACK_T_LBRACE)){black_set_error(e,cur(&p)->location,"kernel requires a block");black_free_program(pr);return NULL;}eat(&p,BLACK_T_LBRACE);while(!is(&p,BLACK_T_RBRACE)&&!is(&p,BLACK_T_EOF)){BlackDecl*d=decl(&p);if(!d){black_free_program(pr);return NULL;}pr->decls=realloc(pr->decls,(pr->count+1)*sizeof(*pr->decls));pr->decls[pr->count++]=d;}eat(&p,BLACK_T_RBRACE);}else if(is(&p,BLACK_T_TARGET)||is(&p,BLACK_T_ABI)){int abi=is(&p,BLACK_T_ABI);p.i++;eat(&p,BLACK_T_LPAREN);if(!is(&p,BLACK_T_STRING)){black_set_error(e,cur(&p)->location,"target/abi requires a string");black_free_program(pr);return NULL;}char*v=black_xstrndup(cur(&p)->text+1,cur(&p)->length-2);p.i++;eat(&p,BLACK_T_RPAREN);eat(&p,BLACK_T_SEMI);if(abi){free(pr->abi);pr->abi=v;}else{free(pr->target);pr->target=v;}}else{BlackDecl*d=decl(&p);if(!d){black_free_program(pr);return NULL;}pr->decls=realloc(pr->decls,(pr->count+1)*sizeof(*pr->decls));pr->decls[pr->count++]=d;}}return pr;}
